/* Database schema to keep the structure of entire database. */

CREATE DATABASE vet_clinic;

CREATE TABLE animals(
id INT PRIMARY KEY,
name VARCHAR,
date_of_birth DATE,
escape_attempts INT,
neutered BOOLEAN,
weitght_kg DECIMAL);

ALTER TABLE animals
ADD species TEXT ;

--Create a table named owners
CREATE TABLE owners(
id INT GENERATED ALWAYS AS IDENTITY,
full_name VARCHAR,
age INT,
PRIMARY KEY (id));

--Create a table named species
CREATE TABLE species(
id INT GENERATED ALWAYS AS IDENTITY,
name VARCHAR,
PRIMARY KEY (id));


--Modifying animals table:
--Make sure that id is set as autoincremented PRIMARY KEY
ALTER TABLE animals
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY ;

--Remove column species.
ALTER TABLE ANIMALS
DROP COLUMN species;

--Add column species_id which is a foreign key referencing species table
ALTER TABLE animals
ADD COLUMN species_id INT;

ALTER TABLE animals
ADD CONSTRAINT fk_species_id
FOREIGN KEY(species_id)
REFERENCES species (id);

--Add column owner_id which is a foreign key referencing the owners table
ALTER TABLE animals
ADD COLUMN owner_id INT;

ALTER TABLE
ALTER TABLE animals
ADD CONSTRAINT fk_owner_id
FOREIGN KEY(owner_id)
REFERENCES owners(id);